apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-workshop
  namespace: kubernetes-workshop
spec:
  ingressClassName: nginx
  rules:
    - host: workshop.fit
      http:
        paths:
          - backend:
              service:
                name: servicea-service
                port:
                  number: 8080
            path: /
            pathType: Prefix