apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea-deployment
  namespace: kubernetes-workshop
  labels:
    app: servicea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicea
  template:
    metadata:
      labels:
        app: servicea
    spec:
      containers:
        - name: servicea
          image: duizhang/k8s-workshop-servicea
          env:
            - name: VERSION
              value: "v1.0"
            - name: UPSTREAM_SERVICE
              value: "serviceb-service:8080"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: servicea-service
  namespace: kubernetes-workshop
spec:
  selector:
    app: servicea
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080